
FROM quay.io/centos/centos:stream8

RUN yum install -y wget python39 python39-pip git

COPY check.py /check.py
RUN pip3.9 install \
  'ipaddress==1.0.*' \
  'icmplib>2.1.0,<3.1.0' \
  'exabgp==4.2.21' && \
  chmod +x /check.py && \
  mkdir -p -m 0750 /usr/local/run/exabgp/ && \
  /usr/bin/mkfifo /usr/local/run/exabgp/exabgp.in && \
  /usr/bin/mkfifo /usr/local/run/exabgp/exabgp.out

RUN mkdir /etc/exabgp

ENTRYPOINT [ "python3.9" ]
