---

version: "3.9"
services:
  exabgp:
    networks:
      exabgp:
        ipv4_address: 10.89.1.2
    platform: linux/amd64
    command: /usr/local/bin/exabgp /etc/exabgp/exabgp.conf
    build:
      context: .
      dockerfile: ./Dockerfile-stream8-python39
    volumes:
      - "$PWD/exabgp.conf:/etc/exabgp/exabgp.conf"
      - "$PWD/exabgp.env:/etc/exabgp/exabgp.env"
    ports:
      - 9203:9203
  bird:
    networks:
      exabgp:
        ipv4_address: 10.89.1.3
    platform: linux/amd64
    image: pierky/bird:2.0.9
    command: bird -f -c /etc/bird/bird.conf
    volumes:
      - "$PWD/bird.conf:/etc/bird/bird.conf"

networks:
  exabgp:
    ipam:
      driver: default
      config:
        - subnet: 10.89.1.0/24
